version: '3'
services:
  discounts:
    build: discounts-service
    ports:
      - "9001:5001"
    depends_on:
      - db
  frontend:
    build: store-frontend/src
    ports:
      - "9000:3000"
    depends_on:
      - db
      - discounts
      - advertisements
  advertisements:
    build: ads-service
    ports:
      - "9002:5002"
    depends_on:
      - db
  db:
    image: postgres:11-alpine
    restart: always
    environment:
      - POSTGRES_PASSWORD
      - POSTGRES_USER
